name: weatheredit
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - altair==5.5.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - appdirs==1.4.4
      - asttokens==3.0.1
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - blinker==1.9.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - clean-fid==0.1.35
      - click==8.3.1
      - clip==1.0
      - cmake==4.1.2
      - colorlog==6.10.1
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dash==3.3.0
      - decorator==5.2.1
      - diffusers==0.25.1
      - docker-pycreds==0.4.0
      - docstring-parser==0.17.0
      - dominate==2.9.1
      - einops==0.8.1
      - embreex==2.17.7.post7
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastapi==0.121.3
      - fastjsonschema==2.21.2
      - ffmpy==1.0.0
      - filelock==3.20.0
      - flask==3.1.2
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.43.0
      - google-auth-oauthlib==0.4.6
      - gradio==3.43.1
      - gradio-client==0.5.0
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jaxtyping==0.3.3
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - kornia==0.7.2
      - kornia-rs==0.1.10
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - lit==18.1.8
      - lpips==0.1.4
      - lxml==6.0.2
      - manifold3d==3.3.2
      - mapbox-earcut==2.0.0
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.2
      - mypy-extensions==1.1.0
      - narwhals==2.12.0
      - nbformat==5.5.0
      - nerfview==0.0.3
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nodeenv==1.9.1
      - numpy==1.26.4
      - nvdiffrast==0.3.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - open-clip-torch==3.2.0
      - open3d==0.16.0
      - opencv-python==4.6.0.66
      - orjson==3.11.4
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pathtools==0.1.2
      - peft==0.13.0
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.5.0
      - plotly==5.13.1
      - prompt-toolkit==3.0.52
      - protobuf==3.20.3
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycollada==0.9.2
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydeck==0.9.1
      - pydub==0.25.1
      - pygments==2.19.2
      - pyliblzfse==0.4.1
      - pyparsing==3.2.5
      - pyquaternion==0.9.9
      - pyre-extensions==0.0.23
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytorch-msssim==1.0.0
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - retrying==1.4.2
      - rich==14.2.0
      - rpds-py==0.29.0
      - rsa==4.9.1
      - rtree==1.4.1
      - safetensors==0.7.0
      - scikit-image==0.20.0
      - scikit-learn==1.7.2
      - scipy==1.11.1
      - semantic-version==2.10.0
      - sentry-sdk==2.45.0
      - setproctitle==1.3.7
      - shapely==2.1.2
      - shtab==1.8.0
      - six==1.17.0
      - smmap==5.0.2
      - smplx==0.1.28
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - starlette==0.50.0
      - streamlit==1.51.0
      - streamlit-keyup==0.2.0
      - svg-path==7.0
      - sympy==1.14.0
      - tenacity==9.1.2
      - tensorboard==2.11.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==0.9.5
      - tokenizers==0.15.2
      - toml==0.10.2
      - torch==2.0.0+cu117
      - torchaudio==2.0.2
      - torchdata==0.6.1
      - torchmetrics==0.10.3
      - torchvision==0.15.0+cu117
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.35.2
      - trimesh==4.9.0
      - triton==2.0.0
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tyro==0.9.35
      - tzdata==2025.2
      - urllib3==1.26.20
      - uvicorn==0.38.0
      - vhacdx==0.0.9
      - viser==0.2.1
      - wadler-lindig==0.1.7
      - wandb==0.15.8
      - watchdog==6.0.0
      - wcwidth==0.2.14
      - websockets==11.0.3
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.15
      - xformers==0.0.18
      - xxhash==3.6.0
      - yourdfpy==0.0.58
      - zipp==3.23.0
prefix: /home/chenghao/miniconda3/envs/weatheredit
